name: wibex
channels:
    - conda-forge
dependencies:
    - python
    - django
    - django-allauth
    - django-environ
    - mysqldb
    - Pillow
    - pip
    - numpy # to create horn chips
    - opencv # to create horn chips
    - whitenoise # to serve static files in production
    - pip:
          - django-debug-toolbar
          - django-filer
          - django-filer\[heif\] # support .heic images


    # - mpm:
    #     - tailwindcss
    #     - clean-css-cli # got some warnings
