name: wibex
channels:
    - conda-forge
dependencies:
    - python
    - django
    - django-allauth
    - django-environ
    - mysqldb
    - Pillow
    - pip
    - numpy
    - opencv # to create horn chips
    - whitenoise # to serve static files in production
    - tensorflow # to run embedding model
    - pip:
          - django-debug-toolbar
          - django-filer
          - django-filer\[heif\] # support .heic images

    - mpm:
          - tailwindcss
          - clean-css-cli # got some warnings
