name: wibex
channels:
    - conda-forge
dependencies:
    - python
    - django
    - django-allauth
    - django-environ
    - mysqldb
    - Pillow
    - pip
    - numpy # to create horn chips
    - opencv # to create horn chips
     - pip:
       - django-debug-toolbar
       - django-filer
       - django-filer\[heif\] # support .heic images
       
