# Generated by Django 5.0.2 on 2024-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_code", models.CharField(blank=True, max_length=8, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("marked", models.BooleanField(default=False)),
                ("capture_date", models.DateField(blank=True, null=True)),
                ("cohort", models.CharField(blank=True, max_length=4, null=True)),
                ("sex", models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
