# Generated by Django 5.0.2 on 2024-04-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_animal"),
        ("filer", "0017_image__transparent"),
    ]

    operations = [
        migrations.CreateModel(
            name="IbexImage",
            fields=[
                ("_height", models.FloatField(blank=True, null=True)),
                ("_width", models.FloatField(blank=True, null=True)),
                ("_transparent", models.BooleanField(default=False)),
                (
                    "default_alt_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="default alt text",
                    ),
                ),
                (
                    "default_caption",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="default caption",
                    ),
                ),
                (
                    "subject_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="subject location",
                    ),
                ),
                (
                    "file_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s_file",
                        serialize=False,
                        to="filer.file",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("filer.file",),
        ),
    ]
