# Generated by Django 5.0.2 on 2024-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ibeximage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibeximage",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("R", "right"), ("L", "left"), ("O", "other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
