# Generated by Django 5.0.2 on 2024-06-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ibeximage_side_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibeximage",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("L", "left"), ("R", "right"), ("O", "other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
