# Generated by Django 5.0.2 on 2024-08-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embedding",
            name="ibex_chip",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ibexchip",
            ),
        ),
    ]
