# Generated by Django 5.0.2 on 2024-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_delete_embedding_if_ibexchip_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
