# Generated by Django 5.0.11 on 2025-02-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_circularregion_and_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibeximage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.location",
            ),
        ),
    ]
