# Generated by Django 5.0.11 on 2025-02-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_owner_field_to_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibeximage",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_region_name_per_owner"
            ),
        ),
    ]
