# Generated by Django 5.0.11 on 2025-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0018_change_image_location_to_ontoone_field_and_constrain_region_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gps", "location from camera GPS"),
                    ("manual", "location manually set on map"),
                    ("region", "location somewhere within this region"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
