# Generated by Django 5.0.11 on 2025-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_source_to_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="exif_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="exif_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
