# Generated by Django 5.0.11 on 2025-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_exif_coordinate_fields_to_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gps", "location from camera GPS"),
                    ("marker", "location marker set manually"),
                    ("region", "location somewhere within this region"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
