# Generated by Django 5.0.11 on 2025-02-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_location_source_naming"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.region",
            ),
        ),
    ]
