# Generated by Django 5.0.11 on 2025-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_region_to_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibeximage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
    ]
