# Generated by Django 5.0.2 on 2024-06-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("simple_landmarks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landmark",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="x_coordinate",
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="y_coordinate",
        ),
        migrations.CreateModel(
            name="LandmarkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_coordinate", models.PositiveBigIntegerField()),
                ("y_coordinate", models.PositiveIntegerField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "landmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simple_landmarks.landmark",
                    ),
                ),
            ],
        ),
    ]
