# Generated by Django 5.0.2 on 2024-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_landmarks", "0002_separate_landmark_and_landmark_item_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmarkitem",
            name="x_coordinate",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="landmarkitem",
            name="y_coordinate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
