# Generated by Django 5.0.2 on 2024-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simple_landmarks",
            "0003_allow_empty_coordinate_values_to_initialise_landmarks",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmarkitem",
            name="x_coordinate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
